# Generated by Django 5.0 on 2023-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0002_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
