# Generated by Django 5.0 on 2023-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0003_alter_userprofile_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='savings',
            field=models.FloatField(default=0),
        ),
    ]
