# Generated by Django 5.0 on 2023-12-12 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0006_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='budget_tracker.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='budget_tracker.userprofile'),
            preserve_default=False,
        ),
    ]
